import type { ToolKnowledge } from './types';

export const cline: ToolKnowledge = {
  tool: 'Cline',
  slug: 'cline',
  aliases: ['cline', 'claude dev'],
  intro: 'Cline is an open-source, model-agnostic AI coding assistant that runs as a VS Code extension: you bring your own API key and it drives the editor through tool calls you approve.',
  reference: [
    {
      heading: 'Model routing per task type',
      body: "Cline lets you assign different models to different jobs instead of running one model for everything. The most direct lever is in the API configuration settings: a toggle to use separate models for Plan mode and Act mode — the exact wording and where it lives in the settings panel shifts release to release, so if it's not where you remember, check the current API configuration screen — so you can put a fast, cheap model on Plan (scoping the approach) and a stronger model on Act (writing the actual code). Beyond that built-in split, most people build an informal routing habit: a small fast model for boilerplate and repetitive edits, a mid-tier model for regular feature work, and a frontier reasoning model with extended thinking for architecture decisions or a bug you've been stuck on. Switching models mid-task is a dropdown change, not a restart — you can bump up to a stronger model the moment a cheap one starts flailing. There's no automatic router that picks the model for you based on task complexity; the routing decision is manual, made by whoever configured the workspace.",
    },
    {
      heading: 'Workspace context & the .clineignore file',
      body: "Cline's most reliable context comes from what you deliberately put in front of it — @ mentions, drag-and-drop, and whatever it reads or edits through its own file tools during a task — plus the running task and conversation history. Cline's requests do carry some ambient environment detail in the background (which files are open, what's visible in the editor), but current guidance treats that as a background signal, not something to rely on the way you'd rely on an explicit @ mention — if a file matters to the task, mention it directly. A .clineignore file at your workspace root, using the same glob syntax as .gitignore, tells Cline which files and folders it isn't allowed to read or edit. Typical entries: node_modules, build output directories, lockfiles, .env and other secret files, and any vendored or generated code that's just noise for an agent. This isn't just a nice-to-have: without a .clineignore, Cline can end up pulling far more of your repo into its starting context than the task needs — adding one is commonly the difference between a 200k-token starting context and one under 50k, which shows up directly as cost and response time. One thing worth knowing before you build a workflow around it: Cline has said it's moving away from .clineignore as a supported feature and plans to deprecate it, so don't treat it as a permanent fixture — check current release notes for what replaces it before you lean on it long-term. Files blocked by .clineignore still show up in Cline's file list — marked with a 🔒 lock prefix rather than hidden — but it's not a hard access wall: a listed file can still get pulled in through an explicit @ mention or a shell command, so don't treat it as a substitute for keeping real secrets out of the repo. On a long task, Cline also condenses context automatically as you approach the active model's limit — a feature called Auto Compact summarizes earlier turns instead of just truncating them, for models it supports, with a manual /compact command if you want to trigger it yourself, falling back to simpler rule-based truncation on models it doesn't support.",
    },
    {
      heading: 'File & command approval policy (auto-approve behavior)',
      body: "By default Cline asks for your approval before every file edit and every terminal command — nothing gets written or executed without you clicking approve first. An auto-approve panel in the chat input lets you turn on specific categories individually — separate toggles for reading and editing files, for running commands Cline considers safe versus running any command at all, for using the browser tool, for using MCP servers, and a few smaller housekeeping ones. The exact set and labels have grown and shifted across releases, so treat the panel itself as the source of truth rather than a fixed list written down somewhere. Older Cline versions had a setting that capped how many actions it would auto-approve back-to-back before pausing to ask again — it was called Max Requests and defaulted to 20. Current Cline (v4.0+) removed that cap, so don't count on a built-in ceiling stopping a runaway; the real protection is keeping file edits and state-changing commands on manual approval in the first place. The sane default for most people: auto-approve reads and safe/read-only commands, keep file edits and anything that mutates state — installs, migrations, git operations, deletes — on manual approval. Auto-approving 'execute all commands' is the single riskiest toggle in the panel; that's the one to leave off unless you're watching closely.",
    },
    {
      heading: 'MCP server configuration',
      body: "Cline is an MCP client — it can connect to any Model Context Protocol server and use its tools inside a coding session: a Postgres server for live schema, a Linear or GitHub server for tickets and issues, a filesystem server scoped outside your workspace, whatever exposes an MCP interface. Servers are registered in a JSON config file (commonly named cline_mcp_settings.json) that you open and edit from the MCP icon in the Cline sidebar — click the MCP Servers icon in the top toolbar, open the Configure tab, then Configure MCP Servers — with entries following the same command / args / env shape used by Claude Desktop's MCP config. Exactly where that file lives on disk has moved around as Cline has grown beyond a single VS Code extension, so open it from the sidebar rather than hardcoding a path. Cline also ships an MCP Marketplace inside the extension — a curated list of popular servers you can install in a couple of clicks, with Cline handling the cloning, setup, and configuration itself instead of you hand-writing the JSON. One feature worth knowing about: you can ask Cline itself, in plain language, to find or build a new MCP server for a tool you need, and it will look up how, scaffold it, and register it as part of the conversation. Keep auth tokens for these servers in environment variables or your OS keychain rather than pasted directly into the JSON file, especially if that file could end up in version control.",
    },
    {
      heading: 'Running Cline (install as a VS Code extension; local/no-account models via Ollama or LM Studio)',
      body: "Cline installs like any other VS Code extension — open the Extensions panel, search 'Cline', install, and a new icon shows up in the sidebar. It also runs in several VS Code-adjacent editors, including Cursor, Windsurf, and VSCodium, plus separate JetBrains, Zed, and Neovim integrations, and it now ships as a standalone CLI too, beyond just the editor extension. That footprint keeps growing, so treat any specific compatibility list, including this one, as a snapshot rather than a promise. The first time you open it, Cline asks you to pick an API provider and paste in a key — Anthropic, OpenAI, and OpenRouter are supported directly, along with cloud providers like AWS Bedrock, GCP Vertex AI, and Azure OpenAI, plus 30-plus more documented providers (Groq, Fireworks, Together, Mistral, xAI, and others) if you want something specific. If you don't want a hosted API at all, set the provider to Ollama or LM Studio: install and run either one locally, pull a model, and Cline talks to it over the local server. Cline pre-fills the standard local ports (Ollama's default is http://localhost:11434, LM Studio's is http://localhost:1234) — that's a sensible default for a standard install, not Cline actively detecting a server running on a different port, so if you've moved it, set the base URL yourself. That path needs no account and no API key, and the model inference itself runs on your machine — but it's not a guaranteed fully offline mode: the extension's own updates and telemetry, any MCP servers you've wired up, and the browser tool can still make network calls regardless of which model is answering. The other real tradeoff is running a smaller, less capable model than a frontier hosted API, and needing hardware that can actually run it at usable speed.",
    },
    {
      heading: 'Model selection & model IDs',
      body: "How you pick a model depends on the provider, and it's less uniform than a single curated-dropdown-everywhere story. Some providers — Ollama is a good example — give you a dropdown populated from what you've actually got installed (your locally pulled models, in Ollama's case), so you're choosing from a list, not typing anything. Others, like a custom OpenAI-compatible endpoint, ask you to type or paste the exact model-ID string the provider expects, because there's no way for Cline to know in advance what you're running there. Where any given provider falls on that spectrum has shifted before and will again, so the reliable move is to open the model picker for the provider you're actually using and see what it asks for, rather than assuming one pattern applies everywhere. What matters more than memorizing exact ID strings is picking by capability tier: the fastest/cheapest model in a family for repetitive mechanical edits, the mid-tier model for regular day-to-day work, and the top-tier reasoning model — with extended thinking turned on if the provider offers it — for architecture calls and hard bugs.",
    },
    {
      heading: 'Modes (Plan/Act) and Cline Rules for customization',
      body: "Cline runs in two built-in modes, toggled from the chat input: Plan mode, where it reads code and talks through an approach without touching files or running commands, and Act mode, where it actually makes edits and executes commands. The habit worth building is staying in Plan mode until you're confident Cline understands the task and has a reasonable approach, then switching to Act and letting it execute — skipping Plan on anything non-trivial is how you end up reviewing a diff full of changes you didn't expect. Cline doesn't have a Roo-Code-style custom-modes system with named personas and per-mode tool restrictions — that's a feature of Roo Code, a well-known fork of Cline, not Cline itself, and it's an easy thing to conflate if you've used both. What Cline does have for customization is Cline Rules: markdown files that get appended to the system prompt when you toggle them on. Global Rules apply everywhere and live outside any one project; Workspace Rules live in a .clinerules/ folder at your project root and apply to that repo specifically. That's prompt customization, not a tool-scoping mechanism — a rule can tell Cline to always write tests first or never touch the migrations folder, but it can't mechanically block a tool call the way a true restricted mode would. If you want something like a debug-only or docs-only persona, a workspace rule that states the constraint clearly is the current way to get there, with the understanding that it's a strong instruction in the prompt, not an enforced restriction.",
    },
    {
      heading: 'Temperature & other model settings',
      body: "Cline doesn't expose a general temperature slider for most hosted providers in its main settings — day-to-day, you steer it through prompts, context, and mode rather than sampling parameters. That's not universal, though: at least the OpenAI-Compatible provider setting has shipped a temperature option, so provider-by-provider behavior varies more than a blanket 'no temperature anywhere' claim would suggest, and it's worth checking your specific provider's settings rather than assuming. In practice the Temperature field currently shows up only under the OpenAI-Compatible provider setting; it's optional, and left blank Cline just uses that provider's own API default rather than imposing one of its own. Most other providers don't surface a temperature control in Cline at all — so if you specifically need to tune it, the OpenAI-Compatible provider path is where that field lives today. If you're running through a local model via Ollama or LM Studio, you have more room to influence generation parameters at the server level — Ollama's Modelfile, LM Studio's per-model settings — regardless of what Cline's own UI surfaces. If precise sampling control matters for your use case, that's usually a sign you want a lower-level API harness rather than an agent extension like Cline.",
    },
    {
      heading: 'Cost control',
      body: "Cline shows the running cost of the current task in the chat UI as it works, so spend is visible while you're working instead of showing up as a surprise later — whether that number reads as per-task, cumulative for the session, or both has varied by version, so read it as a live indicator rather than assuming one fixed meaning. Cline has also added native spend-limit UI — you'll see errors like 'Spend Limit Reached' or 'Quota Exceeded' when a cap is hit — but as it currently works, that appears tied to Cline's own hosted billing (the Cline account / Cline Provider credit balance), not a dollar ceiling you set against your own Anthropic, OpenAI, or other API key. If you're paying with your own key (BYOK), assume the spend limit still needs to be set at the provider: Anthropic Console and OpenAI both support usage limits and spend alerts, and OpenRouter lets you cap a key to a fixed credit balance. That native spend limit only governs Cline's own hosted account and credits — it does not cap spend on a provider API key you brought yourself, so on BYOK don't rely on it as your ceiling. The safe combination is provider-side spend limits (Anthropic Console and OpenAI both support usage caps and alerts; OpenRouter lets you cap a key to a fixed credit balance), a model-routing policy that doesn't run a frontier model on boilerplate, and a sane approval policy so a retry loop can't run unattended.",
    },
  ],
  faqs: [
    {
      q: 'What is a .clineignore file and what goes in it?',
      a: "It's a plaintext file at the root of your workspace, using the same glob syntax as .gitignore, that tells Cline which files and folders it isn't allowed to read or edit. Put node_modules, build output, lockfiles, .env and other secret files, and any vendored or generated code in it — anything that's noise for an agent reading your repo. It matters more than it sounds like it should: without one, Cline can end up loading far more of your project into its starting context than the task needs, which shows up as real dollars and slower responses. It's a soft safety boundary too, not an absolute one — Cline won't read a listed file on its own, but the file can still be pulled in through an explicit @ mention or a shell command, so don't treat it as a substitute for keeping secrets out of the repo entirely. One more thing worth knowing: Cline has said it's deprecating .clineignore, so if you're setting this up today, don't build a workflow that assumes it's permanent — check current docs before leaning on it long-term.",
    },
    {
      q: "How do I stop Cline from making changes I didn't approve?",
      a: "Turn off auto-approve for file edits and for any command that mutates state, and leave them on manual — Cline will show you the diff or the command before it runs and wait for a click. The auto-approve panel in the chat input lets you selectively allow read-only actions — reading files, running commands Cline considers safe — while keeping writes on a leash; the exact set of toggles has grown over time, so look at what's actually in your own panel rather than a fixed list. If you've already turned on broader auto-approval and gotten burned, walk it back to a narrower set: reads and safe commands automatic, everything that writes to disk or your shell manual. Older versions had a cap on consecutive auto-approved actions (the Max Requests setting, default 20); current Cline removed it, so don't count on a built-in limit catching a runaway — the protection that still works is keeping writes and state-changing commands on manual approval.",
    },
    {
      q: 'Which model should Cline use for which task?',
      a: "Match model tier to task difficulty, not habit. Cheap, fast models handle boilerplate, repetitive edits, and simple fixes fine — save the frontier, higher-cost model for architecture decisions, multi-file refactors, and bugs you've already spent real time chasing. Cline supports setting separate models for Plan mode and Act mode in its API configuration settings, so a common pattern is a fast model for Plan, where it's scoping the approach, and a stronger one for Act, where it's actually writing code — check your current settings for exactly where that toggle lives, since it has moved before. If a cheap model starts flailing — misreading the task, looping, producing code that doesn't compile — that's the signal to bump up mid-task rather than let it burn more turns failing at the wrong tier.",
    },
    {
      q: 'How do I set the temperature or other model settings in Cline?',
      a: "Mostly you don't touch it — Cline doesn't expose a general temperature slider for most hosted providers, and steers reliability through prompts, context, and mode rather than sampling parameters for the bulk of setups. That's not a hard rule across every provider, though — at least the OpenAI-Compatible provider setting has shipped a temperature field, so check your specific provider before assuming it's unavailable. Where a temperature field does show up today is the OpenAI-Compatible provider setting; leave it blank and Cline uses that provider's own default rather than setting one itself. Most other providers don't expose a temperature control in Cline at all. If you're running a local model through Ollama or LM Studio, you have more control at that layer — Ollama's Modelfile parameters, LM Studio's per-model settings — even when Cline's own UI doesn't surface them directly.",
    },
    {
      q: 'Can I run Cline without an account or API key?',
      a: "Yes — set your API provider to Ollama or LM Studio instead of a hosted service, and Cline talks to a model running on your own machine over a local server, no account or API key required. What that buys you is local inference and zero marginal cost per request, not a guaranteed fully offline mode — the extension itself can still phone home for updates and telemetry, and anything else you've wired up (MCP servers, the browser tool) makes its own network calls regardless of which model answers your prompt. You give up the capability of a frontier hosted model in exchange for that privacy and cost profile, and you need enough local hardware to run a model at usable speed. Install Ollama or LM Studio, pull a model, and point Cline's provider settings at the local endpoint — Cline pre-fills the standard ports (Ollama http://localhost:11434, LM Studio http://localhost:1234), which works out of the box for a standard install.",
    },
    {
      q: 'How do I configure an MCP server in Cline?',
      a: "Open the MCP Servers icon in the Cline sidebar's top toolbar, go to the Configure tab, and click Configure MCP Servers — that opens the JSON config listing your servers by name with their command, args, and env, commonly named cline_mcp_settings.json. Add one entry per server — the same shape as Claude Desktop's MCP config, if you've set that up before. Exactly where that file lives on disk has shifted as Cline has grown beyond a single VS Code extension, so open it from the sidebar rather than hunting for a hardcoded path. Cline also has a built-in MCP Marketplace for installing popular servers with a couple of clicks instead of hand-editing JSON — Cline handles the cloning and setup itself. Keep any auth tokens the server needs in environment variables rather than hardcoded in the JSON, especially if that config file could end up committed to a repo.",
    },
    {
      q: 'Cline vs Cursor vs Claude Code — which should I use?',
      a: "They solve overlapping problems differently. Cursor is a full VS Code fork with the AI built into the editor and a paid subscription that bundles model access — the smoothest experience if you don't mind switching editors and paying a flat fee. Claude Code is a terminal-first CLI agent from Anthropic, Claude-only, built for people who live in the command line. Cline is an extension for the VS Code you already use, model-agnostic — bring your own key for Claude, GPT, Gemini, or a local model. In my experience that gives you more direct, hands-on control over routing, context, and MCP servers than the other two, at the cost of more configuration work landing on you instead of being handled for you. If you want to stay in your current editor and choose your own model economics, Cline. If you want the tightest built-in editor experience and don't mind a subscription, Cursor. If you want a terminal-native agent and are all-in on Claude, Claude Code.",
    },
    {
      q: 'Why is Cline slow or burning through my API credits?',
      a: "Three usual suspects. Wrong model for the task — running a frontier reasoning model on a simple lint fix costs real money for no benefit. Bloated context — if your .clineignore is thin or missing, Cline can end up pulling far more of the repo into its starting context than the task needs, which costs both money and latency (this is also the exact reason Cline gives for having .clineignore in the first place, even as it plans to move away from it — worth watching what replaces it). And a silent retry loop — a tool call fails, Cline retries with more context attached, fails again, repeats, and the bill climbs while nothing gets fixed. Check the running cost indicator in the chat UI first to see if a specific turn spiked, then look at which model was active and how large the context was on that turn — that usually points straight at the cause.",
    },
    {
      q: 'What are Cline modes (Plan vs Act)?',
      a: "Plan mode is read-only — Cline looks at your code and talks through an approach without editing anything or running commands. Act mode is where it actually does the work: editing files, running the terminal, making the changes you approved (or auto-approved). The habit that saves the most rework is staying in Plan until you're confident Cline has the right approach, then switching to Act to execute — skipping straight to Act on anything non-trivial is how you end up with a diff full of changes you didn't expect. What Cline doesn't have is a Roo-Code-style custom-modes system with named personas and per-mode tool restrictions — that's a feature of Roo Code, a fork of Cline, and it's easy to conflate the two if you've used both. Cline's actual customization mechanism is Cline Rules: markdown files (Global Rules that apply everywhere, Workspace Rules in a .clinerules/ folder at your project root) that get appended to the system prompt when toggled on — it shapes behavior through instructions, not by mechanically restricting which tools are available.",
    },
  ],
};
